# Generated by Django 3.0.6 on 2020-06-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchcontender',
            options={'verbose_name': 'contender', 'verbose_name_plural': 'contenders'},
        ),
        migrations.AlterModelOptions(
            name='tournamentcontender',
            options={'verbose_name': 'contender', 'verbose_name_plural': 'contenders'},
        ),
    ]
